version: "3.8"
services:
  spark:
    cpus: ${CPUS}
    cpuset: "${CPUSET}"
    image: apache/spark-py:v3.3.1
    user: root
    deploy:
      resources:
        limits:
          memory: 24G
    volumes:
      - .:/pagerank
      - ../datasets:/data
      - ../results:/results
    command: bash -c "pip install psutil && cd /pagerank && python3 run.py --repeat ${REPEAT} --iterations ${ITERATIONS} --scripts ${SCRIPTS} --datasets ${DATASETS} --cores ${CPUS} --memory ${MEMORY}"
