version: "3.8"
services:
  zookeeper:
    extends:
      file: common-services.yml
      service: zookeeper-common
  kafka:
    extends:  
      file: common-services.yml
      service: kafka-common
  streamer:
    extends:
      file: common-services.yml
      service: streamer-common
    
    depends_on:
      spark-word-count:
        condition: service_started
      
  stats-collector:
    extends:
      file: common-services.yml
      service: stats-collector-common

  spark-word-count:
    cpuset: $TESTED_CPU_SET
    build: ../services/spark-word-count/
    environment:
      - AUTOCOMMIT_FREQUENCY_MS
      - BENCHMARK_TYPE
      - COMMIT_FREQUENCY
      - RATE_PER_SECOND
      - CORES
      - WORKERS
