version: "3.8"
services:
  zookeeper:
    extends:
      file: common-services.yml
      service: zookeeper-common
  kafka:
    extends:  
      file: common-services.yml
      service: kafka-common
  streamer:
    extends:
      file: common-services.yml
      service: streamer-common
    
    depends_on:
      flink-wordcount-worker:
        condition: service_started
      flink-wordcount-taskmanager:
        condition: service_started

  stats-collector:
    extends:
      file: common-services.yml
      service: stats-collector-common

  flink-wordcount-taskmanager:
    cpuset: $TESTED_CPU_SET
    build: ../services/flink-word-count-scala
    command: taskmanager --job-classname App --commit_interval ${AUTOCOMMIT_FREQUENCY_MS}
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - AUTOCOMMIT_FREQUENCY_MS
      - BENCHMARK_TYPE
      - COMMIT_FREQUENCY
      - ENGINE_TYPE
      - RATE_PER_SECOND
      - CORES
      - WORKERS
      - STATS_SHORT
      - STATS_TIMELINE
      - STATS_PATHWAY_PTIME_AGGREGATED
      - |
        FLINK_PROPERTIES=
        taskmanager.rpc.address: flink-wordcount-taskmanager
        jobmanager.rpc.address: flink-wordcount-worker
        parallelism.default: 1

  flink-wordcount-worker:
    cpuset: $TESTED_CPU_SET
    build: ../services/flink-word-count-scala
    command: standalone-job --job-classname App --commit_interval ${AUTOCOMMIT_FREQUENCY_MS}
    depends_on:
      kafka:
        condition: service_healthy
      flink-wordcount-taskmanager:
        condition: service_started

    environment:
      - AUTOCOMMIT_FREQUENCY_MS
      - BENCHMARK_TYPE
      - COMMIT_FREQUENCY
      - ENGINE_TYPE
      - RATE_PER_SECOND
      - CORES
      - WORKERS
      - STATS_SHORT
      - STATS_TIMELINE
      - STATS_PATHWAY_PTIME_AGGREGATED
      - |
        FLINK_PROPERTIES=
        taskmanager.rpc.address: flink-wordcount-taskmanager
        jobmanager.rpc.address: flink-wordcount-worker
        parallelism.default: 1
