version: "3.8"
services:
  zookeeper:
    extends:
      file: common-services.yml
      service: zookeeper-common
  kafka:
    extends:  
      file: common-services.yml
      service: kafka-common
  streamer:
    extends:
      file: common-services.yml
      service: streamer-common
    
    depends_on:
      pathway-all:
        condition: service_started
      
  stats-collector:
    extends:
      file: common-services.yml
      service: stats-collector-common

  pathway-all:
    cpuset: $TESTED_CPU_SET
    build:
      context: ../../../
      dockerfile: ./public/pathway-benchmarks/services/pathway-all/Dockerfile-local
      args:
        PUBLIC_PATHWAY_DIR: ${PUBLIC_PATHWAY}
        THIRD_PARTY_DIR: ${THIRD_PARTY}
        DOT_GIT_DIR: ${DOT_GIT}
        LOCAL_BUILD_FLAG: ${LOCAL_BUILD}
    deploy:
      resources:
        limits:
          memory: 32G
    cap_add:
      - SYS_PTRACE
    environment:
      - AUTOCOMMIT_FREQUENCY_MS
      - BENCHMARK_TYPE
      - COMMIT_FREQUENCY
      - RATE_PER_SECOND
      - CORES
      - WORKERS
      - PATHWAY_YOLO_RARE_WAKEUPS
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - "./results:/pathway-all/results"

  