version: "3.8"
services:
  zookeeper:
    extends:
      file: common-services.yml
      service: zookeeper-common
  kafka:
    extends:  
      file: common-services.yml
      service: kafka-common
  streamer:
    extends:
      file: common-services.yml
      service: streamer-common
    
    depends_on:
      flink-wordcount:
        condition: service_started
      
  stats-collector:
    extends:
      file: common-services.yml
      service: stats-collector-common

  flink-wordcount:
    cpuset: $TESTED_CPU_SET
    build: ../services/flink-word-count-scala-local
    # command: taskmanager --job-classname App --commit_interval ${AUTOCOMMIT_FREQUENCY_MS}
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - AUTOCOMMIT_FREQUENCY_MS
      - BENCHMARK_TYPE
      - COMMIT_FREQUENCY
      - ENGINE_TYPE
      - RATE_PER_SECOND
      - CORES
      - WORKERS
      - STATS_SHORT
      - STATS_TIMELINE
      - STATS_PATHWAY_PTIME_AGGREGATED
      - |
        FLINK_PROPERTIES=
        taskmanager.rpc.address: flink-wordcount-taskmanager
        jobmanager.rpc.address: flink-wordcount-worker
        taskmanager.memory.process.size: 20G
        jobmanager.memory.process.size: 20G
        parallelism.default: 1

  # taskmanager.memory.flink.size: 16G
  # taskmanager.memory.task.heap.size: 8G

  